language: node_js
node_js:
- 8
- 10
sudo: required
services:
- docker
env:
  matrix:
  - BROWSER=ie_11_win_10
  - BROWSER=chrome_74_win_10
  - BROWSER=firefox_66_win_10
  - BROWSER=safari_12_mojave
before_install:
- docker pull selenium/standalone-chrome:latest
before_script:
- docker run -d --net=host --shm-size=2g selenium/standalone-chrome:latest
- export DBUS_SESSION_BUS_ADDRESS=/dev/null
script:
- npm install
- 'BROWSER=${BROWSER} npx codeceptjs run'